### ISSUE TITLE
Go Installation Error for httprobe

### ISSUE THREAD

**Issue by adam-greer** [reconness/reconness#129]
**Describe the bug**
When I was following the directions on https://docs.reconness.com/scan/httprobe, I continued to get this error
`Step 63/68 : RUN . ~/.profile && go get github.com/tomnomnom/httprobe`
` ---> Running in 92108c763b91`
`crypto/ecdsa`
`/usr/local/go/src/crypto/ecdsa/ecdsa_noasm.go:16:14: undefined: signGeneric`
`/usr/local/go/src/crypto/ecdsa/ecdsa_noasm.go:21:9: undefined: verifyGeneric`
`ERROR: Service 'web' failed to build: The command '/bin/sh -c . ~/.profile && go get` `github.com/tomnomnom/httprobe' returned a non-zero code: 2`

I ended up adding the following line to the DockerFile which resolved the issue.
`RUN rm -r /usr/local/go/`

The full httprobe agent code looks like for me:

`RUN apt-get update && apt-get install -y git wget`
`RUN rm -r /usr/local/go/`
`RUN wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz`
`RUN tar -C /usr/local -xzf go1.13.4.linux-amd64.tar.gz`
`RUN echo 'export GOROOT=/usr/local/go' >> ~/.profile`
`RUN echo 'export GOPATH=$HOME/go'       >> ~/.profile`
`RUN echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.profile`
`RUN . ~/.profile && go get github.com/tomnomnom/httprobe`

**Comment by gorums** [comment]
Hi @adam-greer I will check that and let you know. thx

**Comment by gorums** [comment]
hi @adam-greer looks like you have more than one version installed in the same docker or try to install that only one time.

RUN apt-get update && apt-get install -y git wget
RUN rm -r /usr/local/go/
RUN wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.13.4.linux-amd64.tar.gz
RUN echo 'export GOROOT=/usr/local/go' >> ~/.profile
RUN echo 'export GOPATH=$HOME/go' >> ~/.profile
RUN echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.profile

**Comment by adam-greer** [comment]
Hey @gorums You are correct, I figured by adding that it would prevent confusion when doing the compose.

**Comment by gorums** [comment]
nice!
