### ISSUE TITLE
Feature Request: Update notes via agent/API

### ISSUE THREAD

**Issue by hiddengearz** [reconness/reconness#155]
I'd like to update the subdomain notes via the an agent/API so if I run an agent that find some useful information it can be stored in the notes field.

e.g suspicious directory or url changed at date xyz

**Comment by gorums** [comment]
I'll add {{notes}} into the scripts parse to allow add notes

**Comment by gorums** [comment]
I added the way to update notes in the subdomain via Agent script. it will ready in the next release.

**Comment by gorums** [comment]
this is done. Now we can use scriptOutput.Note to save in the subdomain notes section.
