### ISSUE TITLE
Feature Request: API to get subdomains, services & directories

### ISSUE THREAD

**Issue by hiddengearz** [reconness/reconness#156]
Could an API be added to allow us to pull a list of all subdomains, services/ports and the directories/url's belonging to that subdomain.

1. For example I could create an agent to pull all the subdomains & spider the one's with web servers running on whatever ports, spider them & return the directories./url's.
2. Then create another agent to check all directories/url's for open redirects & update the vulnerability info in #154

**Comment by gorums** [comment]
This is the same with download the subdomains from the API, I'll create an example how do tho using Go

**Comment by gorums** [comment]
Hey @hiddengearz. I created an example using GO to obtain the list of subdomains

You can run that using the next CMD

`go run Auth.go -b https://localhost:5001 -a api/Auth/Login -u gorums -p gorums -s api/targets/exportSubdomains/Opera/opera.com -f subdomains.csv`

`Auth.go` sourcecode

```
package main

import (
	"io"
	"bytes"
	"encoding/json"
	"flag"
	"io/ioutil"
	"net/http"
	"crypto/tls"
	"os"
)

func Auth(url string, authApi string, username string, password string) string {

	values := map[string]string{"UserName": username, "Password": password}
	jsonValue, _ := json.Marshal(values)
    
	req, err := http.NewRequest("POST", url + "/" + authApi, bytes.NewBuffer(jsonValue))	
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	body, _ := ioutil.ReadAll(resp.Body)

	return string(body)
}

func GetToken(jwt string) string {

	in := []byte(jwt)
	var raw map[string]interface{}
	if err := json.Unmarshal(in, &raw); err != nil {
		panic(err)
	}
	return raw["auth_token"].(string)
}


func ExportSubdomains(url string, subdomainApi string, token string, filepath string) {

	req, err := http.NewRequest("GET", url + "/" + subdomainApi, nil)
	req.Header.Set("Authorization","Bearer " + token)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	 
	out, err := os.Create(filepath)
	if err != nil {
		panic(err)
	}
	defer out.Close()

	// Write the body to file
	_, err = io.Copy(out, resp.Body)
	if err != nil {
		panic(err)
	}
}

func main() {

	url := flag.String("b", "", "BaseUrl")

	username := flag.String("u", "", "Username")
	password := flag.String("p", "", "Password")

	authApi := flag.String("a", "", "Auth API")
	subdomainApi := flag.String("s", "", "Subdomain API")
	filepath := flag.String("f", "", "File Path")

	flag.Parse()

	http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true} 
	
	// Do the authentication and obtain the jwt
	jwt := Auth(*url, *authApi, *username, *password)
	// Get the token to allow us send auth request
	token := GetToken(jwt)	
	// Export subdomains to a file
	ExportSubdomains(*url, *subdomainApi, token, *filepath)
}
```

**Comment by hiddengearz** [comment]
Hey @gorums,

Amazing this looks perfect except one small thing. If I make a wrapper how can I get the 'opera/opera.com'? I image the agent will look something like

`./wrapper -d {domain}`

You'll have to edit the agent and provide `project/rootdomain` each time unless you can do something like

`./warpper -d {project/rootdomain}`

Thanks for working on this!

**Comment by gorums** [comment]
this will work. I'll add {{target}} in the command 
 
`go run Auth.go -b https://localhost:5001 -a api/Auth/Login -u gorums -p gorums -s api/targets/exportSubdomains/{{target}}/{{rootDomain}} -f subdomains.csv`

**Comment by gorums** [comment]
Done! I added {{target}} as part of the command to be replace for the current target

**Comment by hiddengearz** [comment]
Thanks! I'll add this to the wrapper I was working on :)

**Comment by hiddengearz** [comment]
Is it possible to also create an api to pull the open ports for the target domain?

Currently I have a script that uses naabu (similar to masscan) to scan for any open ports. I then run nmap on those ports to get a more detailed analysis. I can port that script as a

**Comment by hiddengearz** [comment]
Is it possible to create an API to get the IP's, ports

I have a personal script that uses massdns, naabu and nmap to do an very efficient port scan and would like to port it to an agent, it works like this:

1. Run massdns to resolve all of the subdomains IP's - (Save IP's to reconless, this can be done currently)
2. I then find the unique IP's from all of the subdomains & send that to Naabu - (use reconless API to get all of the IP's, **this can't be done currently**)
2. Naabu then does a full syn port scan on these IP's to find open ports - (save ports to reconless, this can be done currently)
3. I then do an nmap scan on the open ports found by Naabu - (use reconless API to get all of the open ports, **this can't be done currently**)
4. I then cross check the massdns results to see which IP belongs to which subdomain and update the services/notes (use reconless API to get subdomains and IP's, **can partially be done currently**)

**Comment by gorums** [comment]
this endpoint return all the data about the subdomain you can use that to know the IP & Ports, and more data that you can check in the json

GET api/subdomains/{target}/{rootDomainName}/{subdomain}

Ex

GET api/subdomains/VerizonMedia/yahoo.com/ar.answers.yahoo.com

Response:

{
   "id":"03afa05a-d45c-491e-82c7-92f9697e0143",
   "name":"ar.answers.yahoo.com",
   "createdAt":"2020-07-14T17:49:20.391455",
   "target":"yahoo.com",
   "rootDomain":"ReconNess.Entities.RootDomain",
   **"ipAddress":"76.13.32.153"**,
   "takeover":null,
   "hasHttpOpen":true,
   "isMainPortal":null,
   "isAlive":true,
   "fromAgents":"Sublist3r, ZDNS, Httprobe, Ping",
   "serviceHttp":null,
   **"services":[
      {
         "id":"9743a66f-b078-4103-b88d-4c4f3bef4059",
         "name":"https",
         "port":443
      },
      {
         "id":"ad60a3f5-0cac-4d75-a019-2044e8b3329e",
         "name":"http",
         "port":80
      }**
   ],
   "labels":[

   ]
}
