### ISSUE TITLE
Unable to build docker

### ISSUE THREAD

**Issue by MilindPurswani** [reconness/reconness#197]
**Describe the bug**
When attempting to build docker, I am facing this issue that I have described below. I am using this https://github.com/reconness/reconness-agents/blob/master/Dockerfile 

**To Reproduce**
Follow standard installation procedure, use the provided Dockerfile and issue 
```
docker-compose build 
```

Error:

```
Step 25/61 : RUN /root/go/bin/reconness-universal-wrapper setup -u <reconness username> -p <reconness password> -s <reconness.mydomain.com>
 ---> Running in 1e6213185f9d
/bin/sh: 1: Syntax error: end of file unexpected
ERROR: Service 'web' failed to build: The command '/bin/sh -c /root/go/bin/reconness-universal-wrapper setup -u <reconness username> -p <reconness password> -s <reconness.mydomain.com>' returned a non-zero code: 2
```
**Expected behavior**
As per my knowledge, the server should immediately start.  

I am currently using digitalocean $40 per month.

Let me know if you need more info.

Thanks

**Comment by gorums** [comment]
Hi @MilindPurswani. You need to setup your username, password and where are your running reconness

```
################################################################################################################################################
# Change <reconness username> <reconness password> <reconness.mydomain.com> with your username, password and domain where reconness is running.
#
# Ex.
#
# RUN /root/go/bin/reconness-universal-wrapper setup -u myusername -p mypasssord -s http://mydomainorip.com
#################################################################################################################################################
RUN apt-get update && apt-get install -y git wget unzip
RUN wget https://dl.google.com/go/go1.14.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.14.6.linux-amd64.tar.gz
RUN /usr/local/go/bin/go get -u github.com/hiddengearz/reconness-universal-wrapper
RUN /root/go/bin/reconness-universal-wrapper setup -u <reconness username> -p <reconness password> -s <reconness.mydomain.com>
#########################################################################
```

**Comment by gorums** [comment]
That is the same username and password that you use for the login.

Check this link to know more about the login on ReconNess
https://docs.reconness.com/getting-started/installation#digitalocean

Ex.
RUN /root/go/bin/reconness-universal-wrapper setup -u mysuser -p mypassword -s http://167.77.92.112/

**Comment by MilindPurswani** [comment]
That worked out well!

Thanks :)

I appreciate all your hard work 🥇
