### ISSUE TITLE
ScreenShots support

### ISSUE THREAD

**Issue by hdbreaker** [reconness/reconness#4]
Will be great to see a way to look screenshots of the subdomains found with Sublist3r / Amass, support for Aquatone / Eyewitness as a column in the subdomain list view. This feature will add a lot of value to this tool.

**Comment by gorums** [comment]
We want to integrate support for tools like Aquatone where they can take screenshots of the subdomains and you can see then inside ReconNess Portal

**Comment by gorums** [comment]
Hey @hdbreaker is done too
