### ISSUE TITLE
Hello Dear I can't install pls help me 

### ISSUE THREAD

**Issue by hieroo** [reconness/reconness#544]
postgres uses an image, skipping
Building web
Sending build context to Docker daemon  276.8MB
Step 1/26 : FROM mcr.microsoft.com/dotnet/sdk:6.0.100-bullseye-slim AS build
 ---> c8231459539b
Step 2/26 : WORKDIR /app
 ---> Using cache
 ---> 32e5e673f533
Step 3/26 : RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
 ---> Using cache
 ---> fdb483973751
Step 4/26 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> bb045eae9ad8
Step 5/26 : RUN npm install -g @vue/cli
 ---> Running in be3034abdbbf
/bin/sh: 1: npm: not found
The command '/bin/sh -c npm install -g @vue/cli' returned a non-zero code: 127
ERROR: Service 'web' failed to build : Build failed

**Comment by hieroo** [comment]
node -v                                             
v18.12.1
npm -v                   
9.2.0

**Comment by gsec05** [comment]
Hi @hieroo, please update the Dockerfile line 5 to include installing npm:

`RUN apt-get install -y nodejs npm`

This is what worked for me.
There's also a pull request for this issue already submitted too: https://github.com/reconness/reconness/pull/543

**Comment by gorums** [comment]
The PR was merge. Thx @gsec05. I'll close this ticket
