### ISSUE TITLE
I can't build because of the NPM Issue(s)

### ISSUE THREAD

**Issue by kntbyrn** [reconness/reconness#69]
Host: Ubuntu 18.04
Docker Version: Docker version 19.03.8, build afacb8b7f0
Docker Compose: docker-compose version 1.25.4, build 8d51620a

![Screenshot at 2020-03-23 16-34-57](https://user-images.githubusercontent.com/53249968/77297885-db3ef880-6ce1-11ea-88e5-a88a8d57161d.png)

**Comment by gorums** [comment]
Hi @kntbyrn Are you using DigitalOcean?

**Comment by kntbyrn** [comment]
yes I'm using digitalocean.

**Comment by gorums** [comment]
Hi @kntbyrn  That happened to me using 5/USD droplet. You need to use at least a 10/USD droplet.
