### ISSUE TITLE
Something wrong when add another target

### ISSUE THREAD

**Issue by xxnbyy** [reconness/reconness#84]
I add a target first,then i when i add another target,there is something wrong.It seems when i add another target ,the form don't refresh and the key had been there.The same problem seems been when i add last target and open the target before i added,i start to run the agent ,the agent scan the last tartget i added but not the target i select

![image](https://user-images.githubusercontent.com/20261647/79104077-66228880-7da0-11ea-89d0-b07f099006ad.png)
And the code 
reconness   |   Exception data:
reconness   |     Severity: ERROR
reconness   |     SqlState: 23505
reconness   |     MessageText: duplicate key value violates unique constraint "PK_Targets"
reconness   |     Detail: Key ("Id")=(bdea8f4b-2217-4483-a935-7ee25e480c76) already exists.
reconness   |     SchemaName: public
reconness   |     TableName: Targets
reconness   |     ConstraintName: PK_Targets
reconness   |     File: nbtinsert.c
reconness   |     Line: 570
reconness   |     Routine: _bt_check_unique
reconness   |    --- End of inner exception stack trace ---
reconness   |    at ReconNess.Data.Npgsql.ReconNessContext.CommitAsync(CancellationToken cancellationToken) in /app/DAL/ReconNess.Data.Npgsql/ReconNessContext.cs:line 235
reconness   |    at ReconNess.Service`1.AddAsync(TEntity entity, CancellationToken cancellationToken) in /app/ReconNess/Service.cs:line 153
reconness   |    at ReconNess.Web.Controllers.TargetsController.Post(TargetDto targetDto, CancellationToken cancellationToken) in /app/ReconNess.Web/Controllers/TargetsController.cs:line 76
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
reconness   | --- End of stack trace from previous location where exception was thrown ---
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
reconness   | --- End of stack trace from previous location where exception was thrown ---
reconness   |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
reconness   |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
reconness   |    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
reconness   |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
reconness   |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
reconness   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by gorums** [comment]
Thx @xxnbyy. Trying to replicate these issues.

**Comment by gorums** [comment]
I can nort reproduce this issue I'm going to close this ticket
