### ISSUE TITLE
The reconness allways crash exit

### ISSUE THREAD

**Issue by xxnbyy** [reconness/reconness#86]
I'm use a vps with 2048MB ram and 1vCore cpu,the reconness allways crash exit with code 137
It seems because of the agent result is more and more,when i start some agent,the dotnet process's memory is more and more
![image](https://user-images.githubusercontent.com/20261647/79106762-afc1a200-7da5-11ea-9941-b2fe01f59e1c.png)
Even when i just run the ping agent,the memory of the dotnet process is still increase slowly,i don't know why,but it must not a good result there.
![image](https://user-images.githubusercontent.com/20261647/79106947-0c24c180-7da6-11ea-8a36-dfcc87fdfbc5.png)
And the memory of the dotnet process even never reduce when i don't run any agent,it's really a big problem.

**Comment by gorums** [comment]
you need more memory @xxnbyy
