### ISSUE TITLE
add sort function with the agents tag in the target

### ISSUE THREAD

**Issue by xxnbyy** [reconness/reconness#87]
I hope add a sort function with the agents tag in the target,example ,i can sort the agent with the categories tag or name or the last run.
![image](https://user-images.githubusercontent.com/20261647/79107402-e21fcf00-7da6-11ea-8ac1-e0ce24bc755b.png)

**Comment by gorums** [comment]
I'll group by categories

**Comment by gorums** [comment]
This going to be release tomorrow
