### ISSUE TITLE
there is nothing at The terminal and logs and other problem

### ISSUE THREAD

**Issue by xxnbyy** [reconness/reconness#88]
when i run some agents like nmap or dirsearch,the terminal and the logs don't have any output there but the process is really run,and when the agent run complet,the agent looks like is still run,only i fresh the page the agent is going to be normal,i don't know whether the agent had run over.
![image](https://user-images.githubusercontent.com/20261647/79108958-fc0ee100-7da9-11ea-853e-1e6fe5a16105.png)

**Comment by gorums** [comment]
Hi @xxnbyy. yeah there is an issue with the SignalR that I need to check something the websocket is not connection properly

**Comment by gorums** [comment]
That continue happening the time in time, but we such need to refresh and start working again.
