### ISSUE TITLE
There seems something wrong with the dirsearch

### ISSUE THREAD

**Issue by xxnbyy** [reconness/reconness#89]
the dirsearch seems don't work correctly,when i run the dirsearch agent install in the reconness with my own command,the dirsearch seems don't work, and the terminal and logs output nothing,and there is no result at the Directories tag.But when i scan the target with the dirsearch by myself at my vps,it works good.

**Comment by gorums** [comment]
I working fine here

![image](https://user-images.githubusercontent.com/1503645/82485476-7c131f80-9aa9-11ea-9309-6d5c3734d5ba.png)
