### ISSUE TITLE
Service 'web' failed to build

### ISSUE THREAD

**Issue by notsmartjustnot** [reconness/reconness#9]
Hey there. Cool looking project. Please see my username, but I am having issues building. I attempted on Ubuntu 18.04 within a VM as well as I signed up on DigitalOcean to see if I ruined something. I am getting the same error on both Ubuntu instances.

### Local VM - Ubuntu 18.04
![image](https://user-images.githubusercontent.com/59481226/71733690-66a59d80-2e07-11ea-9b6e-57ef89ad60f1.png)

### DigitalOcean Ubuntu 18.04
![image](https://user-images.githubusercontent.com/59481226/71733728-7cb35e00-2e07-11ea-8635-c20e859d78d9.png)

Googling failed for me sadly. If you can point me in the correct direction I would very much appreciate that!

**Comment by hdbreaker** [comment]
Can you explain step by step what are you executing to build and run the Dockerfile / Docker Compose? I was able to ran the project into DigitalOcean following the installation guide without any problem.

**Comment by gorums** [comment]
Hi @notsmartjustnot. Are you using $5/mo $0.007/hr standard Droplet? Please try to upgrade to $10/mo Droplet at least and build again. That happened to me using $5/mo Droplet sometimes.

**Comment by gorums** [comment]
Hi @notsmartjustnot I found the issue, please pull the last version and try again.
