### ISSUE TITLE
Images Looks Broken in Docs.reconness.com

### ISSUE THREAD

**Issue by Senanfurkan** [reconness/reconness#90]
**Describe the bug**
In the docs.reconness.com, the images seems broken

**To Reproduce**
1. Go to 'https://docs.reconness.com/getting-started/quick-start'

**Screenshots**
![Screen Shot 2020-04-18 at 01 53 30](https://user-images.githubusercontent.com/33626136/79620140-a2931300-8117-11ea-832b-f69a51dfc03f.png)

**Comment by gorums** [comment]
Looks fine now thx
